{
 "title": "DevOps - cert-manager",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [ "k8s" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   },
   {
    "name": "Certificate",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"},name) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time Left",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"} - time()) BY (name,exported_namespace) )",
     "legendFormat": " {{`{{exported_namespace}}`}} / {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status) BY (condition)",
     "legendFormat": "{{`{{condition}}`}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"} - time()) BY (name,exported_namespace)",
     "legendFormat": " {{`{{exported_namespace}}`}} / {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "ACME Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall requests per 2m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status)",
     "legendFormat": "{{`{{status}}`}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  }
 ]
}