apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-ingress-by-host
  labels:
    grafana_cluster_administrator_dashboard: "1"
data:
#https://grafana.com/grafana/dashboards/12559-grafana-loki-dashboard-for-nginx-service-mesh/
#https://grafana.com/grafana/dashboards/13865-fgc-nginx01-web-analytics/
  glueops-ingress-by-host.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 47,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": true,
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Total"
                },
                "properties": [
                  {
                    "id": "custom.cellOptions",
                    "value": {
                      "mode": "gradient",
                      "type": "gauge"
                    }
                  },
                  {
                    "id": "color",
                    "value": {
                      "mode": "continuous-BlPu"
                    }
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Agent"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 289
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 17,
            "w": 7,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": [
              {
                "desc": true,
                "displayName": "Total"
              }
            ]
          },
          "pluginVersion": "10.0.1",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "editorMode": "code",
              "expr": "topk(10, sum by (http_user_agent) (count_over_time({app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Top User Agents",
          "transformations": [
            {
              "id": "reduce",
              "options": {
                "labelsToFields": true,
                "reducers": [
                  "sum"
                ]
              }
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Field": true
                },
                "indexByName": {},
                "renameByName": {
                  "Field": "",
                  "Max": "Requests",
                  "http_user_agent": "Agent"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": true,
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Requests"
                },
                "properties": [
                  {
                    "id": "custom.cellOptions",
                    "value": {
                      "mode": "gradient",
                      "type": "gauge"
                    }
                  },
                  {
                    "id": "color",
                    "value": {
                      "mode": "continuous-BlPu"
                    }
                  },
                  {
                    "id": "custom.width",
                    "value": 325
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Agent"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 300
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 17,
            "w": 10,
            "x": 7,
            "y": 0
          },
          "id": 4,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": [
              {
                "desc": true,
                "displayName": "Requests"
              }
            ]
          },
          "pluginVersion": "10.0.1",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "editorMode": "code",
              "expr": "topk(10, sum by (uri) (count_over_time({app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Top Requested Paths",
          "transformations": [
            {
              "id": "reduce",
              "options": {
                "labelsToFields": true,
                "reducers": [
                  "sum"
                ]
              }
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Field": true
                },
                "indexByName": {},
                "renameByName": {
                  "Field": "",
                  "Max": "Requests",
                  "Total": "Requests",
                  "http_user_agent": "Agent",
                  "remote_addr": "IP Address",
                  "uri": "URI"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": true,
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Requests"
                },
                "properties": [
                  {
                    "id": "custom.cellOptions",
                    "value": {
                      "mode": "gradient",
                      "type": "gauge"
                    }
                  },
                  {
                    "id": "color",
                    "value": {
                      "mode": "continuous-BlPu"
                    }
                  },
                  {
                    "id": "custom.width",
                    "value": 325
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Agent"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 300
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 17,
            "w": 7,
            "x": 17,
            "y": 0
          },
          "id": 3,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": []
          },
          "pluginVersion": "10.0.1",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "editorMode": "code",
              "expr": "topk(10, sum by (remote_addr) (count_over_time({app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Top IPs",
          "transformations": [
            {
              "id": "reduce",
              "options": {
                "labelsToFields": true,
                "reducers": [
                  "sum"
                ]
              }
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Field": true
                },
                "indexByName": {},
                "renameByName": {
                  "Field": "",
                  "Max": "Requests",
                  "Total": "Requests",
                  "http_user_agent": "Agent",
                  "remote_addr": "IP Address"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 17
          },
          "id": 6,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "editorMode": "code",
              "expr": "topk(10, sum by (status) (count_over_time({app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))",
              "legendFormat": "{{`{{status}}`}}",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Count by Response Codes",
          "transformations": [],
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "s"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 17
          },
          "id": 7,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "editorMode": "code",
              "expr": "quantile_over_time(0.95,{app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (http_host)",
              "legendFormat": "{{`{{status}}`}}",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "95th percentile of Request Time",
          "transformations": [],
          "type": "timeseries"
        }
      ],
      "refresh": "",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "isNone": true,
              "selected": false,
              "text": "None",
              "value": ""
            },
            "datasource": {
              "type": "loki",
              "uid": "P8E80F9AEF21F6940"
            },
            "definition": "",
            "hide": 0,
            "includeAll": false,
            "label": "",
            "multi": false,
            "name": "host",
            "options": [],
            "query": {
              "label": "http_host",
              "refId": "LokiVariableQueryEditor-VariableQuery",
              "stream": "{app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\"}",
              "type": 1
            },
            "refresh": 2,
            "regex": "\\b(?!-)(?:[a-zA-Z0-9-]{1,63}(?<!-)\\.)+[a-zA-Z]{2,63}\\b",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Ingress by Host",
      "uid": "FViU_A-4k2",
      "version": 9,
      "weekStart": ""
    }
