{
 "title": "Kubernetes Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=\"node-exporter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes Ready",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes not ready",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CPU",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (cluster) (instance:node_num_cpu:sum{cluster=\"test\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(machine_memory_bytes)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "DaemonSets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_ready{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_ready{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(kube_pod_status_ready{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[5m]) + avg_over_time(node_memory_Cached_bytes[5m]) + avg_over_time(node_memory_Buffers_bytes[5m])) / avg_over_time(node_memory_MemTotal_bytes[5m])))",
       "legendFormat": "{{`{{instance}}`}}"
      }
     ]
    },
    {
     "title": "Network Receive by Device and Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{}[$__rate_interval])*8",
       "legendFormat": "recv {{`{{device}}`}}-{{`{{instance}}`}}"
      }
     ]
    },
    {
     "title": "Network Transmission by Device and Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{}[$__rate_interval])*8",
       "legendFormat": "{{`{{device}}`}}-{{`{{instance}}`}}"
      }
     ]
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace= \"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace =\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods not running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\" , namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container!=''} * on(pod) group_left(label_app_kubernetes_io_name) max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_name!=''})) by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers in CrashloopBackOff",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\",container!=''} * on(pod) group_left(label_app_kubernetes_io_name) max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_name!=''})) by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU intensive Apps",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}* on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name) * 100"
    },
    {
     "expr": "sum( cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"} * on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name) * 1000"
    },
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}* on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)/sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"} * on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name))*100"
    },
    {
     "expr": "sum( cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"} * on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name) * 1000"
    },
    {
     "expr": "(sum( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}* on(namespace,pod)group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)/sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}* on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name))*100"
    }
   ]
  },
  {
   "title": "Memory Intensive Apps",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", image!=\"\"}* on(namespace,pod)group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{ namespace=\"$namespace\"}* on(namespace,pod)group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", image!=\"\"}* on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)/sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{ namespace=\"$namespace\"}* on(namespace,pod)group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name))*100"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{ namespace=\"$namespace\"}* on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", image!=\"\"}* on(namespace,pod) group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name)/sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{ namespace=\"$namespace\"}* on(namespace,pod)group_left(label_app_kubernetes_io_name) kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}) by (label_app_kubernetes_io_name))*100"
    }
   ]
  },
  {
   "title": "CPU throttle by Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",container!=''} * on(pod) group_left(label_app_kubernetes_io_name) max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_name!=''})) by (label_app_kubernetes_io_name)",
     "legendFormat": "{{`{{label_app_kubernetes_io_name}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=''} * on(pod) group_left(label_app_kubernetes_io_name) max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_name!=''})) by (label_app_kubernetes_io_name)",
     "legendFormat": "{{`{{label_app_kubernetes_io_name}}`}}"
    }
   ]
  },
  {
   "title": "Containers OOM Killed by pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",container!=''} * on(pod) group_left(label_app_kubernetes_io_name) max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_name!=''})) by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth by Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])* on(pod) group_left(label_app_kubernetes_io_name)max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}))   by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts by pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container!=''} * on(pod) group_left(label_app_kubernetes_io_name) max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_name!=''})) by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])* on(pod) group_left(label_app_kubernetes_io_name)max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}))   by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth By Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])* on(pod) group_left(label_app_kubernetes_io_name)max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}))   by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])* on(pod) group_left(label_app_kubernetes_io_name)max by (pod, label_app_kubernetes_io_name) (kube_pod_labels{namespace=\"$namespace\" ,label_app_kubernetes_io_name!=''}))   by (label_app_kubernetes_io_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Requests By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\"}[5m])*60) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "sum(span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\",http_status_code=\"^5.*\"}) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topK(5,histogram_quantile(0.95, sum(rate(span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\"}[5m])*60) by (le, service_name)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests from TOP 10 IPs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topK(10,sum(span_metrics_calls_total{net_peer_ip!='',span_kind=\"SPAN_KIND_SERVER\",service_name=\"nginx-proxy\"}) by(net_peer_ip)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", http_status_code!=\"\"} / span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", http_status_code!=\"\"}) by (service_name))",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "Status Code by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (http_status_code, service_name) ( rate(span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\"}[5m]) ) * 60",
     "legendFormat": "[{{`{{http_status_code}}`}}] {{`{{service_name}}`}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "filters": [
      { "id": "4a9e5eb9", "operator": "=", "scope": "span" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces with Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "filters": [
      { "id": "965f7c02", "operator": "=", "scope": "span" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}