{
 "title": "DevOps - GlueOps Network Exporter Metrics",
 "description": "https://github.com/syepes/network_exporter/",
 "tags": [
  "VictoriaMetrics",
  "PingStation"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "station",
    "label": "Station",
    "query": {
     "query": "label_values(ping_loss_percent, instance)"
    }
   },
   {
    "name": "name_icmp",
    "label": "Target ICMP",
    "query": {
     "query": "label_values(ping_loss_percent{instance=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_mtr",
    "label": "Target MTR",
    "query": {
     "query": "label_values(mtr_hops{instance=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_tcp",
    "label": "Target TCP",
    "query": {
     "query": "label_values(tcp_connection_status{instance=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_http",
    "label": "Target HTTP",
    "query": {
     "query": "label_values(http_get_status{instance=~\"$station\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Standard Deviation Statistics (Jitter)",
     "type": "graph",
     "description": "- SD: Squared deviation\n- USD: Standard deviation without correction\n- CSD: Standard deviation with correction (Bessel's)\n- RANGE: Max-Min value range",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "last_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"sd\" }[$__interval])",
       "legendFormat": "SD"
      },
      {
       "expr": "last_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"usd\" }[$__interval])",
       "legendFormat": "USD"
      },
      {
       "expr": "last_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"csd\" }[$__interval])",
       "legendFormat": "CSD"
      },
      {
       "expr": "last_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"range\" }[$__interval])",
       "legendFormat": "RANGE"
      }
     ]
    },
    {
     "title": "Response time / Packet loss ($station)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "last_over_time(min_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"best\"}[$__interval])[$__interval:])",
       "legendFormat": "{{`{{type}}`}}-{{`{{target_ip}}`}}"
      },
      {
       "expr": "last_over_time(avg_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"mean\"}[$__interval])[$__interval:])",
       "legendFormat": "{{`{{type}}`}}-{{`{{target_ip}}`}}"
      },
      {
       "expr": "last_over_time(max_over_time(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"worst\"}[$__interval])[$__interval:])",
       "legendFormat": "{{`{{type}}`}}-{{`{{target_ip}}`}}"
      },
      {
       "expr": "ping_loss_percent{instance=~\"$station\",name=~\"$name_icmp\"}",
       "legendFormat": "loss-{{`{{target_ip}}`}}"
      }
     ]
    },
    {
     "title": "Packet loss (All)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "ping_loss_percent{instance=~\"$station\"} < 100 > 0",
       "legendFormat": "{{`{{name}}`}}"
      }
     ]
    },
    {
     "title": "Packet loss per Location",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ping_loss_percent{name=~\"$name_icmp\"}",
       "legendFormat": "{{`{{instance}}`}}-{{`{{target_ip}}`}}"
      }
     ]
    },
    {
     "title": "Response time per Location",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(ping_rtt_seconds{name=~\"$name_icmp\", type=\"mean\"}[$__interval])) by (instance)",
       "legendFormat": "mean - {{`{{instance}}`}} "
      }
     ]
    }
   ]
  },
  {
   "title": "MTR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hops",
     "type": "stat",
     "description": "Number of network HOPS",
     "gridPos": { "h": 26, "w": 2, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mtr_hops{instance=~\"$station\",name=~\"$name_mtr\"}",
       "legendFormat": "{{`{{target}}`}}"
      }
     ]
    },
    {
     "title": "MTR - Mean",
     "type": "graph",
     "description": "Mean Response time",
     "gridPos": { "h": 11, "w": 22, "x": 2, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sort(last_over_time(avg_over_time(mtr_rtt_seconds{instance=~\"$station\",name=~\"$name_mtr\", type=\"mean\"}[$__interval])[$__interval:]))",
       "legendFormat": "{{`{{ttl}}`}} - {{`{{path}}`}} - {{`{{target_ip}}`}}"
      }
     ]
    },
    {
     "title": "MTR - Loss",
     "type": "graph",
     "description": "Packet loss in percent",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort(last_over_time(avg_over_time(mtr_rtt_seconds{instance=~\"$station\",name=~\"$name_mtr\", type=\"loss\"}[$__interval])[$__interval:]))",
       "legendFormat": "{{`{{ttl}}`}} - {{`{{path}}`}}"
      }
     ]
    },
    {
     "title": "Hops - Changes",
     "type": "graph",
     "description": "Number of network HOPS Changes",
     "gridPos": { "h": 5, "w": 22, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "changes(mtr_hops{name=~\"$name_mtr\"}[$__interval]) > 0",
       "legendFormat": "{{`{{instance}}`}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tcp_connection_status{instance=~\"$station\",name=~\"$name_tcp\"}",
       "legendFormat": "{{`{{target}}`}}:{{`{{port}}`}}"
      }
     ]
    },
    {
     "title": "Connection time",
     "type": "graph",
     "description": "Response time",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(tcp_connection_seconds{instance=~\"$station\",name=~\"$name_tcp\"}[$__interval])",
       "legendFormat": "{{`{{target_ip}}`}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Get",
     "type": "graph",
     "description": "Download Drilldown",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(http_get_seconds{instance=~\"$station\",name=~\"$name_http\"}) by (instance,type)",
       "legendFormat": "{{`{{type}}`}}"
      }
     ]
    },
    {
     "title": "HTTP Get - Time",
     "type": "graph",
     "description": "Total Download time",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(http_get_seconds{name=~\"$name_http\", type=\"Total\"}) by (instance)",
       "legendFormat": "{{`{{station}}`}} "
      }
     ]
    },
    {
     "title": "HTTP Get - Speed",
     "type": "graph",
     "description": "Download Speed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "max(http_get_content_bytes{name=\"$name_http\"}) by (instance) / avg(http_get_seconds{type=\"Total\",name=\"$name_http\"}) by (instance)",
       "legendFormat": "{{`{{station}}`}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Target Status by Type",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      { "expr": "ping_up{}", "legendFormat": "ICMP - {{`{{instance}}`}}" },
      { "expr": "mtr_up{}", "legendFormat": "MTR - {{`{{instance}}`}}" },
      { "expr": "tcp_up{}", "legendFormat": "TCP - {{`{{instance}}`}}" },
      { "expr": "http_get_up{}", "legendFormat": "HTTPGet - {{`{{instance}}`}}" }
     ]
    },
    {
     "title": "Active Targets by Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ping_targets{}) by (instance)",
       "legendFormat": "ICMP - {{`{{instance}}`}}"
      },
      {
       "expr": "sum(mtr_targets{}) by (instance)",
       "legendFormat": "MTR - {{`{{instance}}`}}"
      },
      {
       "expr": "sum(tcp_targets{}) by (instance)",
       "legendFormat": "TCP - {{`{{instance}}`}}"
      },
      {
       "expr": "sum(http_get_targets{}) by (instance)",
       "legendFormat": "HTTPGet - {{`{{instance}}`}}"
      }
     ]
    },
    {
     "title": "go goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{instance=\"$station\"}) by (instance)",
       "legendFormat": "{{`{{station}}`}}"
      }
     ]
    },
    {
     "title": "go process resident memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$station\"}",
       "legendFormat": "{{`{{instance}}`}}"
      }
     ]
    }
   ]
  }
 ]
}