apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
  labels:
    app: strimzi
  name: kafka-resources-metrics
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus
    relabelings:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
      replacement: $1
      separator: ;
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: kubernetes_pod_name
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node_name
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_host_ip
      targetLabel: node_ip
  selector:
    matchExpressions:
    - key: strimzi.io/kind
      operator: In
      values:
      - Kafka
      - KafkaConnect
      - KafkaConnector
