{
 "title": "Tempo Operational",
 "tags": [ "tempo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "logsds", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tempo_build_info,namespace)"
    }
   },
   {
    "name": "component",
    "query": "block-builder,compactor,distributor,ingester,metrics-generator,query-frontend,querier,cortex-gw,cortex-gw-internal"
   },
   { "name": "latency_metrics", "label": "Latency metrics", "query": "native : -1,classic : 1" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\".*$component.*\", container!=\"POD\"}[$__rate_interval])",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{ namespace=\"$namespace\", pod=~\".*$component.*\", container!=\"POD\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "tx/rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\".*$component.*\"}[$__rate_interval])",
     "legendFormat": "rx-{{`{{pod}}`}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{ namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "tx-{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "data volume free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\".*$component.*\"}",
     "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promtail_custom_bad_words_total{ exported_namespace=\"$namespace\", app=~\".*$component.*\"}[$__rate_interval])",
     "legendFormat": "{{`{{exported_pod}}`}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "%age total work queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tempodb_work_queue_length{ namespace=\"$namespace\", job=~\"$namespace/$component\"} / tempodb_work_queue_max{namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "maintenance errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempodb_compaction_errors_total{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "compaction_err"
    },
    {
     "expr": "sum(increase(tempodb_retention_errors_total{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "retention_err"
    },
    {
     "expr": "sum(increase(tempodb_blocklist_poll_errors_total{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "blocklist_err"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (le)) < ($latency_metrics * +Inf)",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (le)) < ($latency_metrics * +Inf)",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (le)) < ($latency_metrics * +Inf)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (le)) < ($latency_metrics * -Inf)",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (le)) < ($latency_metrics * -Inf)",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (le)) < ($latency_metrics * -Inf)",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Blocklist Length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tempodb_blocklist_length{ namespace=\"$namespace\", job=~\"$namespace/$component\"}) by (tenant)",
     "legendFormat": "{{`{{tenant}}`}}"
    }
   ]
  },
  {
   "title": "retention duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/compactor\"}[$__rate_interval])) by (le)) < ($latency_metrics * +Inf)",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/compactor\"}[$__rate_interval])) by (le)) < ($latency_metrics * +Inf)",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/compactor\"}[$__rate_interval])) by (le)) < ($latency_metrics * +Inf)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds{ namespace=\"$namespace\", job=~\"$namespace/compactor\"}[$__rate_interval]))) < ($latency_metrics * -Inf)",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds{ namespace=\"$namespace\", job=~\"$namespace/compactor\"}[$__rate_interval]))) < ($latency_metrics * -Inf)",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds{ namespace=\"$namespace\", job=~\"$namespace/compactor\"}[$__rate_interval])) ) < ($latency_metrics * -Inf)",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "retention",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempodb_retention_deleted_total{namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval]))",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[5m]) > 0",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Queries/Sec (Query Frontend)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{namespace=\"$namespace\", route=~\".*traces_traceid\", job=\"$namespace/query-frontend\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{`{{status_code}}`}}"
    }
   ]
  },
  {
   "title": "Query Latency (Query Frontend)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$namespace/query-frontend\", route=~\".*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/query-frontend\", route=~\".*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/query-frontend\", route=~\".*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Query Frontend)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{ namespace=\"$namespace\", route=~\".*api_search.*\", job=\"$namespace/query-frontend\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{`{{status_code}}`}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Query Frontend)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/query-frontend\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/query-frontend\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/query-frontend\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*traces_traceid\",  namespace=\"$namespace\", job=\"$namespace/querier\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{`{{status_code}}`}}"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_search.*\",  namespace=\"$namespace\", job=\"$namespace/querier\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{`{{status_code}}`}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=\"/tempopb.Querier/FindTraceByID\",  namespace=\"$namespace\", job=\"$namespace/ingester\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{`{{status_code}}`}}"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"/tempopb.Querier/Search.*\",  namespace=\"$namespace\", job=\"$namespace/ingester\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{`{{status_code}}`}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Spans Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(tempo_distributor_spans_received_total{ namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(tempo_ingester_traces_created_total{ namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Blocks Flushed (1h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_flushed_total{ namespace=\"$namespace\", job=\"$namespace/ingester\"}[1h]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(tempo_ingester_failed_flushes_total{ namespace=\"$namespace\"}[5m]) > 0",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Blocks Cleared (1h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_cleared_total{ namespace=\"$namespace\"}[1h]))"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_ingester_flush_duration_seconds_bucket{ namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket{ namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_ingester_flush_duration_seconds_bucket{ namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tempo_distributor_queue_length{ namespace=~\"$namespace\", job=~\".*/distributor\"}) by (name)",
     "legendFormat": "{{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Pushes Failing (Distributor)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_metrics_generator_pushes_failures_total{namespace=~\"$namespace\", cluster=~\"$cluster\"}[1m])) by (namespace, cluster)",
     "legendFormat": "{{`{{cluster}}`}} {{`{{namespace}}`}}"
    }
   ]
  },
  {
   "title": "OTEL Distributor Spans/second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_accepted_spans{ namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_receiver_refused_spans{ namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Push Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Memcached", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_memcache_request_duration_seconds_count{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (status_code, method)",
     "legendFormat": "{{`{{status_code}}`}}-{{`{{method}}`}}"
    }
   ]
  },
  {
   "title": "Latency By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".99-{{`{{method}}`}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".9-{{`{{method}}`}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".5-{{`{{method}}`}}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_backend_request_duration_seconds_count{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (status_code, operation)",
     "legendFormat": "{{`{{status_code}}`}}-{{`{{operation}}`}}"
    }
   ]
  },
  {
   "title": "Latency By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_backend_request_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".99-{{`{{operation}}`}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_backend_request_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".9-{{`{{operation}}`}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_backend_request_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".5-{{`{{operation}}`}}"
    }
   ]
  },
  { "title": "Ring/Memberlist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Gossip Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gauge_memberlist_health_score{ namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_memberlist_client_cluster_node_health_score{ namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Member Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(tempo_memberlist_client_cluster_members_count{ namespace=\"$namespace\", job=~\"$namespace/$component\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max(tempo_memberlist_client_cluster_members_count{ namespace=\"$namespace\", job=~\"$namespace/$component\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "KV Store Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(tempo_memberlist_client_kv_store_count{ namespace=\"$namespace\", job=~\"$namespace/$component\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max(tempo_memberlist_client_kv_store_count{ namespace=\"$namespace\", job=~\"$namespace/$component\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Objects Combined / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_combined_total{ namespace=\"$namespace\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Objects Written / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_written_total{ namespace=\"$namespace\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Bytes Written / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (rate(tempodb_compaction_bytes_written_total{ namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Compacted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempodb_compaction_blocks_total{ namespace=\"$namespace\"}[5m])) by (level)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}