{
 "title": "Thanos / Overview",
 "tags": [ "thanos-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  { "title": "Instant Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "description": "Shows rate of requests against /query for the given time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(http_requests_total{handler=\"query\"}[$interval]))",
     "legendFormat": "{{`{{job}}`}} {{`{{handler}}`}} {{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{handler=\"query\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (job) (rate(http_requests_total{handler=\"query\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{handler=\"query\"}[$interval])))",
     "legendFormat": "{{`{{job}}`}} P99"
    }
   ]
  },
  { "title": "Range Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(http_requests_total{handler=\"query_range\"}[$interval]))",
     "legendFormat": "{{`{{job}}`}} {{`{{handler}}`}} {{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query_range.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{handler=\"query_range\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (job) (rate(http_requests_total{handler=\"query_range\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{handler=\"query_range\"}[$interval])))",
     "legendFormat": "{{`{{job}}`}} P99"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "gRPC (Unary) Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "{{`{{job}}`}} {{`{{grpc_method}}`}} {{`{{grpc_code}}`}}"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"unary\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "gRPC Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\"}[$interval])))",
     "legendFormat": "{{`{{job}}`}} P99"
    }
   ]
  },
  { "title": "Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "gRPC (Unary) Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "{{`{{job}}`}} {{`{{grpc_method}}`}} {{`{{grpc_code}}`}}"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"unary\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\"}[$interval])))",
     "legendFormat": "{{`{{job}}`}} P99"
    }
   ]
  },
  { "title": "Receive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Incoming Requests Rate",
   "type": "timeseries",
   "description": "Shows rate of incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(http_requests_total{handler=\"receive\"}[$interval]))",
     "legendFormat": "{{`{{job}}`}} {{`{{handler}}`}} {{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "Incoming Requests Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{handler=\"receive\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (job) (rate(http_requests_total{handler=\"receive\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Incoming Requests Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{handler=\"receive\"}[$interval])))",
     "legendFormat": "{{`{{job}}`}} P99"
    }
   ]
  },
  { "title": "Rule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Alert Sent Rate",
   "type": "timeseries",
   "description": "Shows rate of alerts that successfully sent to alert manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, alertmanager) (rate(thanos_alert_sender_alerts_sent_total{}[$__rate_interval]))",
     "legendFormat": "{{`{{alertmanager}}`}}"
    }
   ]
  },
  {
   "title": "Alert Sent Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of sent alerts.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_alert_sender_errors_total{}[$interval])) / sum by (job) (rate(thanos_alert_sender_alerts_sent_total{}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Alert Sent Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to send alerts to alert manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{}[$interval])))",
     "legendFormat": "{{`{{job}}`}} P99"
    }
   ]
  },
  { "title": "Compact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Compaction Rate",
   "type": "timeseries",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_group_compactions_total{}[$__rate_interval]))",
     "legendFormat": "compaction {{`{{job}}`}}"
    }
   ]
  },
  {
   "title": "Compaction Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_group_compactions_failures_total{}[$interval])) / sum by (job) (rate(thanos_compact_group_compactions_total{}[$interval]))",
     "legendFormat": "error"
    }
   ]
  }
 ]
}