{
 "title": "Thanos / Store",
 "tags": [ "thanos-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(up{job=~\".*thanos*\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Shows rate of execution for operations against the bucket.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operations_total{}[$__rate_interval]))",
       "legendFormat": "{{`{{job}}`}} {{`{{operation}}`}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operation_failures_total{job=~\"$job\"}[$__rate_interval])) / sum by (job, operation) (rate(thanos_objstore_bucket_operations_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{`{{job}}`}} {{`{{operation}}`}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (job, operation, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval]))) * 1",
       "legendFormat": "P99 {{`{{job}}`}}"
      },
      {
       "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operation_duration_seconds_sum{job=~\"$job\"}[$__rate_interval])) * 1  / sum by (job, operation) (rate(thanos_objstore_bucket_operation_duration_seconds_count{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "mean {{`{{job}}`}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (job, operation, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval]))) * 1",
       "legendFormat": "P50 {{`{{job}}`}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Load Rate",
     "type": "timeseries",
     "description": "Shows rate of block loads from the bucket.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_bucket_store_block_loads_total{}[$__rate_interval]))",
       "legendFormat": "block loads"
      }
     ]
    },
    {
     "title": "Block Load Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of block loads from the bucket.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_bucket_store_block_load_failures_total{}[$interval])) / sum by (job) (rate(thanos_bucket_store_block_loads_total{}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Block Drop Rate",
     "type": "timeseries",
     "description": "Shows rate of block drops.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, operation) (rate(thanos_bucket_store_block_drops_total{}[$__rate_interval]))",
       "legendFormat": "block drops {{`{{job}}`}}"
      }
     ]
    },
    {
     "title": "Block Drop Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of block drops.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_bucket_store_block_drop_failures_total{}[$interval])) / sum by (job) (rate(thanos_bucket_store_block_drops_total{}[$interval]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "description": "Show rate of cache requests.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_requests_total{}[$__rate_interval]))",
       "legendFormat": "{{`{{job}}`}} {{`{{item_type}}`}}"
      }
     ]
    },
    {
     "title": "Hits",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of cache hits.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_hits_total{}[$__rate_interval]))",
       "legendFormat": "{{`{{job}}`}} {{`{{item_type}}`}}"
      }
     ]
    },
    {
     "title": "Added",
     "type": "timeseries",
     "description": "Show rate of added items to cache.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_items_added_total{}[$__rate_interval]))",
       "legendFormat": "{{`{{job}}`}} {{`{{item_type}}`}}"
      }
     ]
    },
    {
     "title": "Evicted",
     "type": "timeseries",
     "description": "Show rate of evicted items from cache.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_items_evicted_total{}[$__rate_interval]))",
       "legendFormat": "{{`{{job}}`}} {{`{{item_type}}`}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Sent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk Size",
     "type": "timeseries",
     "description": "Shows size of chunks that have sent to the bucket.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "sum by (job) (rate(thanos_bucket_store_sent_chunk_size_bytes_sum{}[$__rate_interval])) / sum by (job) (rate(thanos_bucket_store_sent_chunk_size_bytes_count{}[$__rate_interval]))",
       "legendFormat": "mean"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "P50"
      }
     ]
    }
   ]
  },
  {
   "title": "Series Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block queried",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_blocks_queried_bucket{}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "sum by (job) (rate(thanos_bucket_store_series_blocks_queried_sum{job=~\"$job\"}[$__rate_interval])) / sum by (job) (rate(thanos_bucket_store_series_blocks_queried_count{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "mean {{`{{job}}`}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_blocks_queried{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Data Fetched",
     "type": "timeseries",
     "description": "Show the size of data fetched",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_data_fetched_bucket{}[$__rate_interval])))",
       "legendFormat": "P99: {{`{{data_type}}`}} / {{`{{job}}`}}"
      },
      {
       "expr": "sum by ( data_type) (rate(thanos_bucket_store_series_data_fetched_sum{}[$__rate_interval])) / sum by (data_type) (rate(thanos_bucket_store_series_data_fetched_count{}[$__rate_interval]))",
       "legendFormat": "mean: {{`{{data_type}}`}} / {{`{{job}}`}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_data_fetched_bucket{}[$__rate_interval])))",
       "legendFormat": "P50: {{`{{data_type}}`}} / {{`{{job}}`}}"
      }
     ]
    },
    {
     "title": "Data Touched",
     "type": "timeseries",
     "description": "Show the size of data touched",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_data_touched{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "P99: {{`{{data_type}}`}} / {{`{{job}}`}}"
      },
      {
       "expr": "sum by (job, data_type) (rate(thanos_bucket_store_series_data_touched_sum{job=~\"$job\"}[$__rate_interval])) / sum by (job, data_type) (rate(thanos_bucket_store_series_data_touched_count{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "mean: {{`{{data_type}}`}} / {{`{{job}}`}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_data_touched{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "P50: {{`{{data_type}}`}} / {{`{{job}}`}}"
      }
     ]
    },
    {
     "title": "Result series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_result_series{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "sum by (job) (rate(thanos_bucket_store_series_result_series_sum{job=~\"$job\"}[$__rate_interval])) / sum by (job) (rate(thanos_bucket_store_series_result_series_count{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "mean {{`{{job}}`}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_result_series{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "P50"
      }
     ]
    }
   ]
  }
 ]
}