{
 "title": "Traefik - Advanced Multi-Namespace",
 "description": "Enhanced Traefik Kubernetes Dashboard with Namespace isolation",
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "lb_name",
    "label": "Namespace (LB Name)",
    "query": "label_values(traefik_entrypoint_requests_total, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(traefik_service_requests_total{namespace=\"$lb_name\"}, service)"
   },
   { "name": "interval", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total{namespace=\"$lb_name\"})"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\", namespace=\"$lb_name\"}[$interval])) by (entrypoint)",
     "legendFormat": "{{`{{entrypoint}}`}}"
    }
   ]
  },
  {
   "title": "Apdex Score (Response Time Quality)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\", namespace=\"$lb_name\"}[$interval])) by (entrypoint) + sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\", namespace=\"$lb_name\"}[$interval])) by (entrypoint)) / 2 / sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\", namespace=\"$lb_name\"}[$interval])) by (entrypoint)",
     "legendFormat": "Apdex: {{`{{entrypoint}}`}}"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Services (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, label_replace(traefik_service_request_duration_seconds_sum{namespace=\"$lb_name\", service=~\"$service.*\",protocol=\"http\"} / traefik_service_request_duration_seconds_count{namespace=\"$lb_name\", service=~\"$service.*\",protocol=\"http\"}, \"service\", \"$1\", \"service\", \"([^@]+)@.*\"))",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "Top 10 High-Traffic Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, label_replace(sum by (service) (rate(traefik_service_requests_total{namespace=\"$lb_name\", service=~\"$service.*\"}[$interval])), \"service\", \"$1\", \"service\", \"([^@]+)@.*\"))",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  }
 ]
}