{
 "title": "DevOps - Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(up{job=\"vault\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(up{job=\"vault\",instance=~\"$node:(.*)\"}, instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": {
     "query": "label_values(vault_secret_kv_count, mount_point)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Status (Just means they are running but not unsealed)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"vault\"}",
     "legendFormat": "{{`{{ instance }}`}}"
    }
   ]
  },
  {
   "title": "Secrets (THIS IS BUGGY)",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count)",
     "legendFormat": "{{`{{ mount_point }}`}}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{`{{ instance }}`}}" }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "CPU/Mem Info: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{})",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_token_count)" }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy)",
     "legendFormat": "{{`{{ policy }}`}}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count - vault_token_store_count)"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl)",
     "legendFormat": "{{`{{ creation_ttl }}`}}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth)",
     "legendFormat": "{{`{{ auth_method }}`}}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation)",
     "legendFormat": "{{`{{ auth_method }}`}} - {{`{{ creation_ttl }}`}}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count)",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Lookups per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  }
 ]
}