apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-vault-errors-alert
  labels:
    grafana_dashboard: "1"
data:
  vault-errors.json: |
    {
        "groups": [
            {
                "orgID": 1,
                "name": "critical_errors",
                "folder": "critical_errors",
                "interval": "60s",
                "rules": [
                    {
                        "uid": "critical_alert_vault",
                        "title": "Vault Error",
                        "condition": "B",
                        "noDataState": "OK",
                        "data": [
                            {
                                "refId": "A",
                                "queryType": "range",
                                "relativeTimeRange": {
                                    "from": 21600,
                                    "to": 0
                                },
                                "datasourceUid": "P8E80F9AEF21F6940",
                                "model": {
                                    "editorMode": "code",
                                    "expr": "rate({namespace=\"glueops-core-vault\"} |~ \".*ERROR.*\" [1m])",
                                    "hide": false,
                                    "intervalMs": 1000,
                                    "legendFormat": "__auto",
                                    "maxDataPoints": 43200,
                                    "range": true,
                                    "refId": "A"
                                }
                            },
                            {
                                "refId": "B",
                                "queryType": "",
                                "relativeTimeRange": {
                                    "from": 21600,
                                    "to": 0
                                },
                                "datasourceUid": "-100",
                                "model": {
                                    "conditions": [
                                        {
                                            "evaluator": {
                                                "params": [
                                                    0,
                                                    0
                                                ],
                                                "type": "gt"
                                            },
                                            "operator": {
                                                "type": "and"
                                            },
                                            "query": {
                                                "params": [
                                                    "A"
                                                ]
                                            },
                                            "reducer": {
                                                "params": [],
                                                "type": "avg"
                                            },
                                            "type": "query"
                                        }
                                    ],
                                    "datasource": {
                                        "name": "Expression",
                                        "type": "__expr__",
                                        "uid": "__expr__"
                                    },
                                    "expression": "A",
                                    "hide": false,
                                    "intervalMs": 1000,
                                    "maxDataPoints": 43200,
                                    "reducer": "last",
                                    "refId": "B",
                                    "type": "classic_conditions",
                                    "window": ""
                                }
                            }
                        ],
                        "for": "5m",
                        "execErrState": "Error"
                    }
                ]
            }
        ]
    }
        